//
// Created by sala on 04/03/2021.
//

#ifndef MINECRAFTBUTACTUALLYGOOD_CONFIG_HPP
#define MINECRAFTBUTACTUALLYGOOD_CONFIG_HPP

#define GAME_NAME "GroundField"
#define GAME_ENGINE_NAME "GroundUp Engine"

#endif //MINECRAFTBUTACTUALLYGOOD_CONFIG_HPP
